//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2018.LiveContest.SocialNetwork
{
    
    
    /// <summary>
    /// The public interface for Comment
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Comment))]
    [XmlDefaultImplementationTypeAttribute(typeof(Comment))]
    [ModelRepresentationClassAttribute("https://www.transformation-tool-contest.eu/2018/social_media#//Comment")]
    public interface IComment : IModelElement, ISubmission
    {
        
        /// <summary>
        /// The commented property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("commented")]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("comments")]
        ISubmission Commented
        {
            get;
            set;
        }
        
        /// <summary>
        /// The likedBy property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("likedBy")]
        [CategoryAttribute("Comment")]
        [XmlElementNameAttribute("likedBy")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("likes")]
        [ConstantAttribute()]
        ISetExpression<IUser> LikedBy
        {
            get;
        }
        
        /// <summary>
        /// Gets fired before the Commented property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> CommentedChanging;
        
        /// <summary>
        /// Gets fired when the Commented property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> CommentedChanged;
    }
}

