FROM ftsrg/ttc2018:common

# dependencies (separated to share layers with other images)
RUN apt-get update && \
    apt-get install -yq --no-install-recommends build-essential cmake \
    && rm -rf /var/lib/apt/lists/*

# install GraphBLAS and LAGraph
WORKDIR /opt
ARG SS_RELEASE=v3.3.3
ARG SS_BURBLE=0
# SS_COMPACT=0 for benchmark, 1 for fast compilation
ARG SS_COMPACT=0

# remove previous GraphBLAS install if exists
RUN rm -f /usr/local/lib/libgraphblas.so* && \
    git clone --depth 1 --branch ${SS_RELEASE} https://github.com/DrTimothyAldenDavis/GraphBLAS && \
    cd GraphBLAS/build && \
    cmake .. -DGB_BURBLE=${SS_BURBLE} -DGBCOMPACT=${SS_COMPACT} && \
    make -j$(nproc) install

RUN git clone --depth 1 https://github.com/GraphBLAS/LAGraph && \
    cd LAGraph/build && \
    cmake .. && \
    make -j$(nproc) install && \
    ldconfig

WORKDIR /ttc

# small and stable files
COPY expected-results expected-results
COPY reporting reporting
COPY scripts scripts
COPY output output

# most frequently changing folders
COPY solutions/GB-Batch-x1/ solutions/GB-Batch-x1/
COPY solutions/GB-Batch-xAll/ solutions/GB-Batch-xAll/
COPY solutions/GB-Incr-x1/ solutions/GB-Incr-x1/
COPY solutions/GB-Incr-xAll/ solutions/GB-Incr-xAll/
COPY solutions/GraphBLAS/ solutions/GraphBLAS/
COPY config/config-docker-graphblas.json config/config.json

# build solutions in config.json
RUN scripts/run.py -b

COPY docker/entrypoint-graphblas.sh entrypoint.sh
CMD ./entrypoint.sh
