FROM ftsrg/ttc2018:common

# dependencies (separated to share layers with other images)
RUN apt-get update && \
    apt-get install -yq --no-install-recommends rustc cargo \
    && rm -rf /var/lib/apt/lists/*

# small and stable files
COPY expected-results expected-results
COPY reporting reporting
COPY scripts scripts
COPY output output

# most frequently changing folders
COPY solutions/differential/ solutions/differential/
COPY solutions/differential-08/ solutions/differential-08/
COPY config/config-docker-differential.json config/config.json

# build solutions in config.json
RUN scripts/run.py -b

COPY docker/entrypoint-differential.sh entrypoint.sh
CMD ./entrypoint.sh
