FROM ftsrg/ttc2018:common

RUN apt-get update && \
    apt-get install -yq --no-install-recommends rustc cargo \
    && rm -rf /var/lib/apt/lists/* \
    # install sccache
    && wget -qO sccache.tar.gz "https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz" \
    && echo "e5d03a9aa3b9fac7e490391bbe22d4f42c840d31ef9eaf127a03101930cbb7ca *sccache.tar.gz" | sha256sum -c --quiet - \
    && tar -zxf sccache.tar.gz \
    && rm sccache.tar.gz \
    && cd sccache-* \
    && chmod u+x sccache \
    && mv sccache /usr/local/bin/
ENV RUSTC_WRAPPER=sccache

# small and stable files
COPY expected-results expected-results
COPY reporting reporting
COPY scripts scripts
COPY output output

# most frequently changing folders
COPY solutions/differential/ solutions/differential/
COPY solutions/differential-08/ solutions/differential-08/
COPY solutions/differential-datalog/ solutions/differential-datalog/
COPY config/config-docker-differential.json config/config.json

# build solutions in config.json
RUN scripts/run.py -b --skip-tests

COPY docker/entrypoint-differential.sh entrypoint.sh
CMD ./entrypoint.sh

# save build information
ARG README_TXT_ARG=""
ENV README_TXT=$README_TXT_ARG
RUN date -Is > README.md
RUN echo "$README_TXT" >> README.md
