ARG BASE_CONTAINER=ubuntu:20.04
FROM ${BASE_CONTAINER}

# to prevent tzdata installer from requiring user input
# https://askubuntu.com/a/1013396/415610
ENV DEBIAN_FRONTEND=noninteractive

# most common dependencies
RUN apt-get update && \
    apt-get install -yq --no-install-recommends python3 r-base unzip ca-certificates apt-transport-https wget git \
    && rm -rf /var/lib/apt/lists/*

# big files, not expected to change
WORKDIR /ttc
COPY models models
RUN cd models && unzip 1024.zip

# dependencies (separated to share layers with other images)
RUN apt-get update && \
    apt-get install -yq --no-install-recommends openjdk-8-jdk-headless maven \
    && update-java-alternatives --set java-1.8.0-openjdk-amd64 \
    && rm -rf /var/lib/apt/lists/*
# pre-download Gradle wrapper (all tools use the same version)
ENV GRADLE_WRAPPER_TOOL_PATH=solutions/EMFSolutionXtend/
COPY $GRADLE_WRAPPER_TOOL_PATH/gradle/wrapper $GRADLE_WRAPPER_TOOL_PATH/gradle/wrapper
COPY $GRADLE_WRAPPER_TOOL_PATH/gradlew $GRADLE_WRAPPER_TOOL_PATH/gradlew
RUN $GRADLE_WRAPPER_TOOL_PATH/gradlew --version

# small and stable files
COPY expected-results expected-results
COPY reporting reporting
COPY scripts scripts
COPY output output

# solution folders
COPY solutions/EMFSolutionAOF solutions/EMFSolutionAOF
COPY solutions/EMFSolutionATL solutions/EMFSolutionATL
COPY solutions/EMFSolutionATL-Incremental solutions/EMFSolutionATL-Incremental
COPY solutions/EMFSolutionTemplate solutions/EMFSolutionTemplate
COPY solutions/EMFSolutionXtend solutions/EMFSolutionXtend
COPY solutions/Hawk solutions/Hawk
COPY solutions/HawkIncUpdate solutions/HawkIncUpdate
COPY solutions/HawkIncUpdateQuery solutions/HawkIncUpdateQuery
COPY solutions/jastadd-ttc18-relast-xml-flush solutions/jastadd-ttc18-relast-xml-flush
COPY solutions/jastadd-ttc18-relast-xml-inc solutions/jastadd-ttc18-relast-xml-inc
COPY solutions/jastadd-ttc18-xml-flush solutions/jastadd-ttc18-xml-flush
COPY solutions/jastadd-ttc18-xml-inc solutions/jastadd-ttc18-xml-inc

# config
COPY config/config-docker-java8.json config/config.json

# build solutions in config.json
RUN scripts/run.py -b

COPY docker/entrypoint-java8.sh entrypoint.sh
CMD ./entrypoint.sh
