FROM ftsrg/ttc2018:common

# dependencies (separated to share layers with other images)
RUN apt-get update && \
    apt-get install -yq --no-install-recommends openjdk-8-jdk-headless maven \
    && update-java-alternatives --set java-1.8.0-openjdk-amd64 \
    && rm -rf /var/lib/apt/lists/*
# pre-download Gradle wrapper (all tools use the same version)
ENV GRADLE_WRAPPER_TOOL_PATH=solutions/EMFSolutionXtend/
COPY $GRADLE_WRAPPER_TOOL_PATH/gradle/wrapper $GRADLE_WRAPPER_TOOL_PATH/gradle/wrapper
COPY $GRADLE_WRAPPER_TOOL_PATH/gradlew $GRADLE_WRAPPER_TOOL_PATH/gradlew
RUN $GRADLE_WRAPPER_TOOL_PATH/gradlew --version

# small and stable files
COPY expected-results expected-results
COPY reporting reporting
COPY scripts scripts
COPY output output

# solution folders
COPY solutions/EMFSolutionAOF solutions/EMFSolutionAOF
COPY solutions/EMFSolutionATL solutions/EMFSolutionATL
COPY solutions/EMFSolutionATL-Incremental solutions/EMFSolutionATL-Incremental
COPY solutions/EMFSolutionTemplate solutions/EMFSolutionTemplate
COPY solutions/EMFSolutionXtend solutions/EMFSolutionXtend
COPY solutions/Hawk solutions/Hawk
COPY solutions/HawkIncUpdate solutions/HawkIncUpdate
COPY solutions/HawkIncUpdateQuery solutions/HawkIncUpdateQuery
COPY solutions/jastadd-ttc18-relast-xml-flush solutions/jastadd-ttc18-relast-xml-flush
COPY solutions/jastadd-ttc18-relast-xml-inc solutions/jastadd-ttc18-relast-xml-inc
COPY solutions/jastadd-ttc18-xml-flush solutions/jastadd-ttc18-xml-flush
COPY solutions/jastadd-ttc18-xml-inc solutions/jastadd-ttc18-xml-inc

# config
COPY config/config-docker-java8.json config/config.json

# build solutions in config.json
RUN scripts/run.py -b

COPY docker/entrypoint-java8.sh entrypoint.sh
CMD ./entrypoint.sh

ENV JAVA_HEAP_SIZE=6G

# save build information
ARG README_TXT_ARG=""
ENV README_TXT=$README_TXT_ARG
RUN date -Is > README.md
RUN echo "$README_TXT" >> README.md
