ARG BASE_CONTAINER=ubuntu:20.04
FROM ${BASE_CONTAINER}

# to prevent tzdata from requiring user input
# https://askubuntu.com/a/1013396/415610
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /ttc
COPY models models
COPY expected-results expected-results
COPY output output
COPY reporting reporting
COPY scripts scripts

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
      openjdk-8-jdk-headless git python3 maven r-base && \
    update-java-alternatives --set java-1.8.0-openjdk-amd64 && \
    rm -rf /var/lib/apt/lists/*

# solution folders
COPY solutions/EMFSolutionAOF solutions/EMFSolutionAOF
COPY solutions/EMFSolutionATL solutions/EMFSolutionATL
COPY solutions/EMFSolutionATL-Incremental solutions/EMFSolutionATL-Incremental
COPY solutions/EMFSolutionXtend solutions/EMFSolutionXtend
COPY solutions/Hawk solutions/Hawk
COPY solutions/HawkIncUpdate solutions/HawkIncUpdate
COPY solutions/HawkIncUpdateQuery solutions/HawkIncUpdateQuery
COPY solutions/jastadd-ttc18-relast-xml-flush solutions/jastadd-ttc18-relast-xml-flush
COPY solutions/jastadd-ttc18-relast-xml-inc solutions/jastadd-ttc18-relast-xml-inc
COPY solutions/jastadd-ttc18-xml-flush solutions/jastadd-ttc18-xml-flush
COPY solutions/jastadd-ttc18-xml-inc solutions/jastadd-ttc18-xml-inc

# config
COPY config/config-docker-java8.json config/config.json

# build solutions in config.json
RUN scripts/run.py -b

# run the benchmark in container
CMD scripts/run.py -mc
