ARG BASE_CONTAINER=ubuntu:20.04
FROM ${BASE_CONTAINER}

# to prevent tzdata installer from requiring user input
# https://askubuntu.com/a/1013396/415610
ENV DEBIAN_FRONTEND=noninteractive

# most common dependencies
RUN apt-get update && \
    apt-get install -yq --no-install-recommends python3 r-base unzip ca-certificates apt-transport-https wget git \
    && rm -rf /var/lib/apt/lists/*

# big files, not expected to change
WORKDIR /ttc
COPY models models
RUN cd models && unzip 1024.zip

# dependencies (separated to share layers with other images)
RUN apt-get update && \
    apt-get install -yq --no-install-recommends openjdk-11-jdk-headless \
    && update-java-alternatives --set java-1.11.0-openjdk-amd64 \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update && \
    apt-get install -yq --no-install-recommends maven \
    && rm -rf /var/lib/apt/lists/*

# small and stable files
COPY expected-results expected-results
COPY reporting reporting
COPY scripts scripts
COPY output output

# most frequently changing folders
COPY solutions/EMFSolutionYAMTL solutions/EMFSolutionYAMTL
COPY solutions/EMFSolutionYAMTL_batch solutions/EMFSolutionYAMTL_batch
COPY config/config-docker-java11.json config/config.json

# build solutions in config.json
RUN scripts/run.py -b

# run the benchmark in container
CMD scripts/run.py -mc
